services:
  timescale-primary:
    image: timescale/timescaledb:latest-pg17
    container_name: timescale-primary
    environment:
      POSTGRES_DB: smart-meters
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_primary:/var/lib/postgresql/data
      - pg_primary_hot_1:/tablespaces/hot_1
      - pg_primary_hot_2:/tablespaces/hot_2
    command: >
      postgres
      -c timescaledb.enable_chunk_skipping=on
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5      
    networks:
      - timescale-network

networks:
  timescale-network:
    driver: bridge

volumes:
  pg_primary:
  pg_primary_hot_1:
  pg_primary_hot_2: